model_list:
  - model_name: tier1
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: "os.environ/GROQ_API_KEY"

  - model_name: tier2
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      api_key: "os.environ/GEMINI_API_KEY"

  - model_name: tier3
    litellm_params:
      model: gemini/gemini-3.8-flash
      api_key: "os.environ/GEMINI_API_KEY"

  - model_name: tier3_fallback
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: "os.environ/GROQ_API_KEY"
